---
title: "Clustering"
author: "Nicolas Beglinger"
date: "12/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preliminaries
```{r, echo = FALSE, message = FALSE}
pkgTest <- function(x) 
  {
    if (!require(x, character.only = TRUE))
    {
      install.packages(x, dep = TRUE)
        if(!require(x, character.only = TRUE)) stop("Package not found")
    }
}

pkgTest("sf")
pkgTest("tidyverse")
pkgTest("dbscan")
pkgTest("tmap")

```

## Read/create data
```{r}
accidents <- st_read("shapefiles/accidents/schwere_unfaelle.shp")

#If too many points:
accidents <- st_read("shapefiles/accidents/schwere_unfaelle_motorrad.shp")

streetLine <- st_read("shapefiles/streetLine/AVZH18_streets_lines.shp")


accCrds <- accidents %>%
  st_coordinates() %>%
  cbind(seq(1:nrow(.)))
colnames(accCrds)[3] <- "ID"


```



## DB Scan
minPts = dimensionality + 1 -> 3
epsylon = search the knee in the distplot -> 300, but doesn't seem reasonable
```{r, echo = FALSE, message = FALSE}
minPts = 4
epsylon = 200

kNNdistplot(accCrds, k = minPts) +
  abline(h = epsylon, col = "red")

db <- dbscan::dbscan(accCrds, eps = epsylon, minPts = minPts)

accidents <- accidents %>%
  mutate(dbCluster = db$cluster,
         dbClusterNaN = ifelse(dbCluster > 0, dbCluster, NA))

head(accidents$dbClusterNaN, n = 10)

# tm_shape(streetLine) +
#   tm_lines(alpha = 0.5) +
# tm_shape(accidents) +
#   tm_dots(
#     col = "dbClusterNaN",
#     style = "quantile",
#     n = 30,
#     colorNA = NULL,
#     legend.show = FALSE
#     
#   )


plot(accCrds, pch = 19, cex = 0.5, col = db$cluster)
```

## Optics
```{r, results = FALSE, log = FALSE, message = FALSE}
eps = 400
minPts = 4
opt <- optics(accCrds, eps = eps, minPts = minPts)
plot(opt)

p<-plot(accCrds, col = "red") +
  polygon(accCrds[opt$order,], border = "lightgrey", lwd = 0.5)

eps_cl = 350
opt <- extractDBSCAN(opt, eps_cl = eps_cl)
plot(opt)

p<-plot(accCrds, cex = 0.4, pch = 19, col = opt$cluster+1)
```

## HDB-scan
```{r}
hdb = hdbscan(accCrds, minPts = 3)

plot(hdb$hc)

plot(accCrds, col = hdb$cluster+1, pch = 1)
```

