---
title: "master_dataframe"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Initialize
```{r, echo = FALSE, message = FALSE}
pkgTest <- function(x) 
  {
    if (!require(x, character.only = TRUE))
    {
      install.packages(x, dep = TRUE)
        if(!require(x, character.only = TRUE)) stop("Package not found")
    }
}

pkgTest("sf")
pkgTest("tidyverse")
pkgTest("tmap")

#for palette explorer
pkgTest("tmaptools")
pkgTest("shiny")
pkgTest("shinyjs")


crs_lv95  <- "+init=epsg:2056"

tmap_mode("view")
source("functions.r")
```


```{r}
accidents <- st_read("shapefiles/accidents/verkehrsunfaelle_stadt_zh_points_new.shp")
accNoHighway <- filter(accidents, RdTyp_n != "Motorway" & RdTyp_n != "Expressway")

bicycle = filter(accidents, AccdnIB == "true")
motorCycle = filter(accidents, AccdnIM == "true")
pedestrians = filter(accidents, AccdnIP == "true")


bicycleSevere = filter(bicycle, AccdSC_ == "Accident with severe injuries" | AccdSC_ == "Accident with fatalities")
motorCycleSevere = filter(motorCycle, AccdSC_ == "Accident with severe injuries" | AccdSC_ == "Accident with fatalities" )
pedestriansSevere = filter(pedestrians, AccdSC_ == "Accident with severe injuries"| AccdSC_ == "Accident with fatalities")


```



```{r}
masterBicycle =  masterDataFrame(bicycle, accNoHighway, motorCycleSevere, focusFilter = 10, alpha = 0.01)
#st_write(masterBicycle, "shapefiles/hexBins/master_bicycle_new.shp")



masterPedestrians = masterDataFrame(pedestrians, accNoHighway, motorCycleSevere, focusFilter = 15, alpha = 0.01)
#st_write(masterMotorCycle, "shapefiles/hexBins/master_pedestrians.shp", append = FALSE)
```


```{r}
masterMotorCycle = masterDataFrame(motorCycle, accidents, motorCycleSevere, focusFilter = 5, alpha = 0.01)

masterMotorCycle <- masterMotorCycle %>%
  arrange(-ratio) %>%
  mutate(rat_rank = seq(1:nrow(.))) %>%
  arrange(p) %>%
  mutate(p_rank = seq(1:nrow(.))) %>%
  mutate(mot_rank = rep(NaN, nrow(.))) %>%
  mutate(sev_rank = rep(NaN, nrow(.)))


masterMotorCycle

st_write(masterMotorCycle, "shapefiles/hexBins/master_motorCycle.shp", append = FALSE)

```

```{r}
masterPedestrians = masterDataFrame(pedestrians, accNoHighway, motorCycleSevere, focusFilter = 5, alpha = 0.01)


masterPedestrians <- masterPedestrians %>%
  arrange(-ratio) %>%
  mutate(rat_rank = seq(1:nrow(.))) %>%
  arrange(p) %>%
  mutate(p_rank = seq(1:nrow(.))) %>%
  mutate(ped_rank = rep(NaN, nrow(.))) %>%
  mutate(sev_rank = rep(NaN, nrow(.)))


masterPedestrians

st_write(masterPedestrians, "shapefiles/hexBins/master_pedestrians.shp", append = FALSE)
```






